# Generated by Django 4.2 on 2023-04-07 13:07

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def split_name(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    worker_model = apps.get_model("company_api", "Worker")

    workers = worker_model.objects.all()

    for worker in workers:
        name = worker.name.split()
        if len(name) == 2:
            worker.last_name, worker.first_name = name
        else:
            worker.last_name, worker.first_name, worker.patronymic = name

    worker_model.objects.bulk_update(workers, ("last_name", "first_name", "patronymic",), batch_size=100)


def join_name(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    worker_model = apps.get_model("company_api", "Worker")

    workers = worker_model.objects.all()

    for worker in workers:
        worker.name = worker.last_name + " " + worker.first_name + (
            " " + worker.patronymic if worker.patronymic else ""
        )

    worker_model.objects.bulk_update(workers, ("name",), batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        (
            "company_api",
            "0002_worker_first_name_worker_last_name_worker_patronymic_and_more",
        ),
    ]

    operations = [migrations.RunPython(split_name, join_name)]
